import type { NextPage } from "next";
import Head from "next/head";
import MainLayout from "../components/MainLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Next app</title>
      </Head>
      <MainLayout>
        <div>
          <h1>Hello next1</h1>
        </div>
      </MainLayout>
    </>
  );
};

export default Home;
